name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (just for the deploy action)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Copy frontend to public/
        run: |
          mkdir public
          cp -r frontend/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
